[package]
name = "mandelbrot-server"
version = "0.1.0"
authors = ["Matthew Gaudet <magaudet@ca.ibm.com>"]

[dependencies]
num = "0.1.27"
image = "0.13.0"
crossbeam = "0.2.8"

iron = "0.5.1"
mime = "0.2.3"
router = "0.5.1"
urlencoded = "0.5.0"
base64 = "0.9.2"